### ISSUE TITLE
Default Admin password!

### ISSUE THREAD

**Issue by arizawan** [StadtBern/SUBMISS#1]
Hello!

I have installed and configured this project as mentioned in the readme. But I did not find any default admin credentials to access the API. Could you help me out, please?

Thanks

**Comment by LoisK** [comment]
There is no default admin user to access the API. And that's why there are no default admin credentials to access the API. 
Create a user via the REST Endpoints and use this created user for your tests.
If you didn't set up an IDP, it is possible to create the user via a Tool that supports SAML based authentication.
